[[setup-manual]]
= Manual Setup
:sectnums:
:icons: font

Are you the type who likes to see all the magic that happens behind the scenes? Or maybe you prefer that things are installed on your system _just so_. In either case, you can can manually install the Million Song Library without using the automated setup script. Just follow the steps in this section.

NOTE: If you want to get up and running as quickly as possible, using the automated setup script is the easiest way to install the Million Song Library demo on a <<Setup-Mac.adoc#setup-mac,Mac>>, <<Setup-Ubuntu.adoc#setup-ubuntu,Linux>>, or <<Setup-Windows.adoc#setup-windows,Windows>> computer.

== Get Your System Ready

Before setting up the demo, make sure all of the following tools are installed on your system and are at the required version or higher.

This procedure assumes that you're running the Million Song Library demo on Mac OS X 10.11 (El Capitan), Ubuntu 14.04 (Trusty Tahr), or Windows 10. Things might work a little differently on other operating systems.

====
*Entering Commands*

We tested these steps using the default Terminal applications on Mac OS X and Ubuntu. To enter commands on Windows 10, we recommend running Windows PowerShell as an Administrator.
====

====
*Where is My Home Directory?*

For this process, it's important to know where your home directory is. Your home directory is the directory that has the same name as your user name.

* On Mac and Linux, your home directory is represented by the tilde (~) sign in Terminal commands.
* On Windows, your home directory is: *C:\Users\<your_username>\*
====

Java 1.8 JDK::

To check the installed version, use the `java -version` command. If necessary, http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[install the Java 1.8 JDK^].

Git::

To check the installed version, use the `git --version` command. If necessary, http://git-scm.com/downloads[install Git^].

IMPORTANT: (Windows only) During Git installation, make sure to select the *Use Git from the Windows Command Prompt* option. Otherwise you won't be able use Git commands in PowerShell.

Maven 3.3.9 or later::

To check the installed version, use the `mvn -version` command. If necessary, http://www.tutorialspoint.com/maven/maven_environment_setup.htm[set up Maven^].

Node 0.12.x or later::

To check the installed version, use the `node --version` command. If necessary, https://nodejs.org/en/download/[install Node^].

npm 2.7.x or later::

To check the installed version, use the `npm -version` command. If necessary, https://nodejs.org/en/download/[install Node, which includes npm^].

Bower::

To check the installed version, use the `bower --version` command. If necessary, https://github.com/bower/bower[install Bower^].

NOTE: If you get a permissions error, use `sudo bower --version` instead.

RubyGem::

To check the installed version, use the `gem --version` command. If necessary, install RubyGem for https://gorails.com/setup/osx/10.11-el-capitan[Mac^], https://gorails.com/setup/ubuntu/14.04[Linux^], or http://rubyinstaller.org/downloads/[Windows^].

AsciiDoctor::

To check the installed version, use the `asciidoctor --version` command. If necessary, http://asciidoctor.org/#installation[install AsciiDoctor^].

Cassandra::
. Download Cassandra 2.1.11 (Community version) from the https://downloads.datastax.com/community/[Datastax download site^].
+
NOTE: Make sure to download the correct file: *dsc-cassandra-2.1.11-bin.tar.gz*
. Create a new directory named *cassandra* inside your home directory.
. Move the *dsc-cassandra-2.1.11-bin.tar.gz* file into the new *cassandra* directory, and then extract the contents into the *cassandra* directory.

Chocolatey (Windows only)::

To check the installed version, use the `choco -v` command. If necessary, https://chocolatey.org/[install Chocolatey^].

Apple Xcode (Mac OS X Only)::

On Mac OS X, some necessary command line tools aren't installed by default, so to get them you'll need to https://developer.apple.com/xcode/download/[install the latest version of Xcode from the Mac App Store^].
+
NOTE: After installation, make sure to open Xcode, accept the license agreement, and (if prompted) install any additional tools.

Enable Root User (Mac OS X Only)::

On Mac OS X, the root user is not enabled by default, so you'll need to enable it so the setup script runs properly. To enable the root user, just https://support.apple.com/en-us/HT204012[follow these instructions^].

== Clone the MSL Repository

. Make sure you are in your home directory.
. Clone the million-song-library repository:
+
----
git clone https://github.com/kenzanmedia/million-song-library
----
. Change directories to the cloned repository:
+
----
cd million-song-library
----
+
. Initialize the repository and submodules:
+
----
git submodule init && git submodule update
----

NOTE: For Windows, you will need to run the commands separately: first `git submodule init` and then `git submodule update`.

== Set up the Client

. Change to the *msl-pages* directory inside the *million-song-library* directory
+
----
cd msl-pages
----
. Download and install all dependencies:
+
----
npm install && bower install
----
+
NOTE: For Windows, you will need to run the commands separately: first `npm install` and then `bower install`.
. Install Protractor and Selenium WebDriver globally:
+
----
npm install -g -y protractor && npm install -g -y selenium-webdriver
----
+
NOTE: For Windows, you will need to run the commands separately: first `npm install -g -y protractor` and then `npm install -g -y selenium-webdriver`.

== Set up the Server

. Change to the *server* directory inside the *million-song-library* directory:
+
----
cd ../server
----
. Run the Maven file to set up the server:
+
----
mvn clean compile
----

== Set up Cassandra

. Open a new Terminal window, or a PowerShell window with administrator privileges.
. Start Cassandra:
+
_Mac or Linux_
+
----
sh ~/cassandra/dsc-cassandra-2.1.11/bin/cassandra
----
+
_Windows_
+
[red]#*TBD - need step for Windows*#
+
----
???
----
. After Cassandra finishes starting, press *<Enter>* to display the command prompt again.
. Enter the Cassandra console:
+
_Mac or Linux_
+
----
sh ~/cassandra/dsc-cassandra-2.1.11/bin/cqlsh
----
+
_Windows_
+
[red]#*TBD - need step for Windows*#
+
----
???
----
. Import data by entering the following commands at the *cqlsh>* prompt, pressing *<Enter>* after each command:
+
----
SOURCE 'msl_ddl_latest.cql';
SOURCE 'msl_dat_latest.cql';
----
+
Wait for the database to import the data -- this will take several minutes.
. Exit the console:
+
----
exit
----

== Start the MSL Demo

. Open a new Terminal window, or a PowerShell window with administrator privileges.
. Change to the application directory: 
+
_Mac or Linux:_
+
----
cd ~/million-song-library/msl-pages
----
+
_Windows:_
+
----
cd C:\Users\<your_username>\million-song-library\msl-pages
----

. Start the application front end:
+
----
npm run full-dev
----
+
Wait for the front end to start up -- this will take just a couple of minutes.
. Open a new Terminal window, or a PowerShell window with administrator privileges.
. Change to the application directory: 
+
_Mac or Linux:_
+
----
cd ~/million-song-library/msl-pages
----
+
_Windows:_
+
----
cd C:\Users\<your_username>\million-song-library\msl-pages
----
. Start the server instances:
+
_Linux:_
+
----
sudo npm run serve-all
----
+
_Mac or Windows:_
+
----
npm run serve-all
----
+
Wait for the server instances to start up -- again, this will take just a couple of minutes.
. Open a Web browser and point it to: *msl.kenzanlabs.com:3000*
+
The Million Song Library home page displays. (If you don't see data right away, wait a couple of minutes and then refresh the page.)

== Stop the MSL Demo

. Switch to the Terminal or PowerShell window where you started the server instances and press *Control+C* to stop the server.
. Switch to the Terminal or PowerShell window where you started the application and press *Control+C* to stop the application.
. Switch to the Terminal or PowerShell window where you started Cassandra and enter the following command:
+
----
ps auwx | grep cassandra
----
+
Look at the output from the command and note the first 3&#8211;5 digit number that appears in the output. This is the process ID for Cassandra.
. Enter the following command where *pid* is the process ID you found (you'll be prompted for your administrator password):
+
----
sudo kill pid
----

[red]#*TBD - Need steps for stopping Cassandra on Windows*#
