[[setup-manual]]
= Manual Setup
:sectnums:
:icons: font

Are you the type who likes to see all the magic that happens behind the scenes? Or maybe you prefer that things are installed on your system _just so_. In either case, you can can manually install the Million Song Library on a Mac or Linux system without using the automated setup script. Just follow the steps in this section.

NOTE: If you want to get up and running as quickly as possible, using the automated setup script is the easiest way to install the Million Song Library demo on a <<Setup-Mac.adoc#setup-mac,Mac>> or <<Setup-Ubuntu.adoc#setup-ubuntu,Linux>> system. Or use Vagrant to automate setup on a <<Setup-Windows.adoc#setup-windows,Windows>> system.

== Get Your System Ready

Before setting up the demo, make sure all of the following tools are installed on your system and are at the required version or higher.

This procedure assumes that you're running the Million Song Library demo on Mac OS X 10.11 (El Capitan) or Ubuntu 14.04 (Trusty Tahr). Things might work a little differently on other operating systems.

====
*Entering Commands*

We tested these steps using the default Terminal applications on Mac OS X and Ubuntu.
====

====
*Where is My Home Directory?*

For this process, it's important to know where your home directory is. Your home directory is the directory that has the same name as your user name.

For example, if the user name you use to log on to your system is jdoe, your home directory is named *jdoe*. In Terminal, your home directory is represented by the tilde (~) sign. For example, the path *~/stuff* points to a directory named *stuff* located inside your home directory.

====

Java 1.8 JDK::

To check the installed version, use the `java -version` command. If necessary, http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[install the Java 1.8 JDK^].

Git::

To check the installed version, use the `git --version` command. If necessary, http://git-scm.com/downloads[install Git^].

Maven 3.3.9 or later::

To check the installed version, use the `mvn -version` command. If necessary, http://www.tutorialspoint.com/maven/maven_environment_setup.htm[set up Maven^].

Node 0.12.x or later::

To check the installed version, use the `node --version` command. If necessary, https://nodejs.org/en/download/[install Node^].

npm 2.7.x or later::

To check the installed version, use the `npm -version` command. If necessary, https://nodejs.org/en/download/[install Node, which includes npm^].

Bower::

To check the installed version, use the `bower --version` command. If necessary, https://github.com/bower/bower[install Bower^].

NOTE: If you get a permissions error, use `sudo bower --version` instead.

RubyGem::

To check the installed version, use the `gem --version` command. If necessary, install RubyGem for https://gorails.com/setup/osx/10.11-el-capitan[Mac^] or https://gorails.com/setup/ubuntu/14.04[Linux^].

AsciiDoctor::

To check the installed version, use the `asciidoctor --version` command. If necessary, http://asciidoctor.org/#installation[install AsciiDoctor^].

Cassandra::
. Download Cassandra 2.1.11 (Community version) from the https://downloads.datastax.com/community/[Datastax download site^].
+
NOTE: Make sure to download the correct file: https://downloads.datastax.com/community/dsc-cassandra-2.1.11-bin.tar.gz[*dsc-cassandra-2.1.11-bin.tar.gz*]
. Create a new directory named *cassandra* inside your home directory.
. Move the *dsc-cassandra-2.1.11-bin.tar.gz* file into the new *cassandra* directory, and then extract the contents into the *cassandra* directory.

Apple Xcode (Mac OS X Only)::

On Mac OS X, some necessary command line tools aren't installed by default, so to get them you'll need to https://developer.apple.com/xcode/download/[install the latest version of Xcode from the Mac App Store^].
+
NOTE: After installation, make sure to open Xcode, accept the license agreement, and (if prompted) install any additional tools.

Enable Root User (Mac OS X Only)::

The setup script requires the use of `sudo` to run certain commands as root. However, on Mac OS X, the root user is not enabled by default. You'll need to enable the root user so that the setup script will run properly.

To enable the root user, just https://support.apple.com/en-us/HT204012[follow these instructions^].

== Clone the MSL Repository

. Make sure you are in your home directory.
. Clone the million-song-library repository:
+
----
git clone https://github.com/kenzanmedia/million-song-library
----
. Change directories to the cloned repository:
+
----
cd million-song-library
----
+
. Initialize the repository and submodules:
+
----
git submodule init && git submodule update
----

== Set up the Client

. Change to the *msl-pages* directory inside the *million-song-library* directory
+
----
cd msl-pages
----
. Download and install all dependencies:
+
----
npm install && bower install
----
+
. Install Protractor and Selenium WebDriver globally:
+
----
npm install -g -y protractor && npm install -g -y selenium-webdriver
----

== Set up the Server

. Change to the *server* directory inside the *million-song-library* directory:
+
----
cd ../server
----
. Run the Maven file to set up the server:
+
----
mvn clean compile
----

[[start-cassandra-manual]]
== Set up Cassandra

. Open a new Terminal window.
. Start Cassandra:
+
----
sh ~/cassandra/dsc-cassandra-2.1.11/bin/cassandra
----
. After Cassandra finishes starting, press *<Enter>* to display the command prompt again.
. Enter the Cassandra console:
+
----
sh ~/cassandra/dsc-cassandra-2.1.11/bin/cqlsh
----
. Import data by entering the following commands at the *cqlsh>* prompt, pressing *<Enter>* after each command:
+
----
SOURCE 'msl_ddl_latest.cql';
SOURCE 'msl_dat_latest.cql';
----
+
Wait for the database to import the data -- this will take several minutes.
. Exit the console:
+
----
exit
----

WARNING: If you get an error when trying to start Cassandra, it probably means that Cassandra is already running (for example, from running the Million Song Library demo previously). To correct this issue, reboot your system, or stop Cassandra (see <<stop-msl-manual>>). Then try starting Cassandra again. You should always make sure to stop Cassandra when you're done working with the Million Song Library demo.

[[start-msl-manual]]
== Start the MSL Demo

. Open a new Terminal window.
. Change to the application directory: 
+
----
cd ~/million-song-library/msl-pages
----
+

. Start the application front end:
+
----
npm run full-dev
----
+
Wait for the front end to start up -- this will take just a couple of minutes.
. Open a new Terminal window.
+
WARNING: Make sure to open a new Terminal tab or window before starting the servers, to avoid stopping the front end.
+
. Change to the application directory: 
+
----
cd ~/million-song-library/msl-pages
----
+
. Start the server instances:
+
_Linux:_
+
----
sudo npm run serve-all
----
+
_Mac:_
+
----
npm run serve-all
----
+
Wait for the server instances to start up -- again, this will take just a couple of minutes.
. Open a Web browser and point it to: *msl.kenzanlabs.com:3000*
+
The Million Song Library home page displays.
+
NOTE: If you don't see data right away, wait a few minutes and then refresh the page. If data still doesn't load, try clearing your web browser cache.

[[stop-msl-manual]]
== Stop the MSL Demo

. Switch to the Terminal window where you started the server instances and press *Control+C* to stop the server.
. Switch to the Terminal window where you started the application and press *Control+C* to stop the application.
. Switch to the Terminal window where you started Cassandra and enter the following command:
+
----
ps auwx | grep cassandra
----
+
Look at the output from the command and note the first 3&#8211;5 digit number that appears in the output. This is the process ID for Cassandra.
. Enter the following command where *pid* is the process ID you found (you'll be prompted for your administrator password):
+
----
sudo kill pid
----

NOTE: You don't need to run the setup script if you want to start the Million Song Library demo again. Just start Cassandra (see <<start-cassandra-manual>>) and then start the application and server instances (see <<start-msl-manual>>).
